###

## Вход в закрытую часть приложения
POST http://localhost:4200/users/login HTTP/1.1
Accept: application/json
Content-Type: application/json


{
  "email": "MarieWilson1995@career.com",
  "password": "123456"
}

> {% client.global.set("token", response.body.token); %}
###

# Фильмы
## Добавить новый фильм
POST http://localhost:4200/movies HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "ABCEGOENWSKN",
  "description": "EFJleo neofGIBEoig boERB Goireb oier bouireb oujer ujb ",
  "postDate": "2022-10-21T22:55:33.903Z",
  "genre": "thriller",
  "releaseYear": 2013,
  "previewUri": "/preview",
  "videoUri": "/video",
  "cast": [
    "Star A",
    "Star B"
  ],
  "director": "Dir /usr",
  "runningLengthMin": 70,
  "posterUri": "hunger_games_poster.jpg",
  "backgroundImageUri": "hunger_games_bg.jpg",
  "backgroundColor": "#789651"
}

> {% client.log(response.body.id); client.global.set("movieId", response.body.id); %}
###

## Редактирование карточки фильма
PATCH http://localhost:4200/movies/{{movieId}} HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Король лев",
  "description": "EFJleo neofGIBEoig boERB Goireb oier bouireb oujer ujb ",
  "postDate": "2022-10-22T22:55:33.903Z",
  "genre": "drama",
  "releaseYear": 2013,
  "previewUri": "/ppreview",
  "videoUri": "/vvideo",
  "cast": [
    "Star B",
    "Star C"
  ],
  "director": "Dir /tmp",
  "runningLengthMin": 10,
  "posterUri": "lion_king_poster.jpg",
  "backgroundImageUri": "lion_king_bg.jpg",
  "backgroundColor": "#788956"
}

###

## Получение детальной информации по фильму
GET http://localhost:4200/movies/{{movieId}} HTTP/1.1
Accept: application/json

###

## Удаление карточки фильма
DELETE http://localhost:4200/movies/{{movieId}} HTTP/1.1
Authorization: Bearer {{token}}

###

## Получить список фильмов
GET http://localhost:4200/movies?limit=5 HTTP/1.1
Accept: application/json

###

## Получение списка фильмов определенного жанра
GET http://localhost:4200/movies?genre=drama HTTP/1.1
Accept: application/json

###

## Получение промо-фильма
GET http://localhost:4200/promo-movie HTTP/1.1
Accept: application/json

###

## Получить список фильмов «К просмотру»
GET http://localhost:4200/movies-to-watch HTTP/1.1
Accept: application/json
Authorization: Bearer {{token}}

###

## Добавить фильм в список «К просмотру»
POST http://localhost:4200/movies-to-watch HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "movieId": "{{movieId}}"
}

###

## Удалить фильм из списка «К просмотру»
DELETE http://localhost:4200/movies-to-watch HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "movieId": "{{movieId}}"
}

###

# Комментарии
## Получить список комментариев для определённого фильма
GET http://localhost:4200/comments?movieId={{movieId}} HTTP/1.1
Accept: application/json

###

## Добавить новый комментарий к определённому фильму
POST http://localhost:4200/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "text": "10/10 gfhjerogn orgeribgo bnerog jbroj ibeor gjibower breo breo gjberojb",
  "score": 10,
  "movieId": "{{movieId}}"
}

###

# Пользователи
## Создание нового пользователя
POST http://localhost:4200/users/register HTTP/1.1
Content-Type: multipart/form-data; boundary=RazDva

--RazDva
Content-Disposition: form-data; name="email"
Content-Type: text/plain

sergei.lugovykh2@yandex.ru
--RazDva
Content-Disposition: form-data; name="name"
Content-Type: text/plain

Sergei
--RazDva
Content-Disposition: form-data; name="password"
Content-Type: text/plain

123456
--RazDva
Content-Disposition: form-data; name="profilePicture"; filename="avatar.png"
Content-Type: image/png

< ./static-directory/default-avatar.png
--RazDva--

> {% client.global.set("registeredUserId", response.body.id); %}
###

## Отправка аватарки пользователя
POST http://localhost:4200/users/{{registeredUserId}}/profilePicture HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="profilePicture"; filename="avatar.png"
Content-Type: image/png

< ./static-directory/avatar.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

POST http://localhost:4200/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "sergei.lugovykh2@yandex.ru",
  "password": "123456"
}

> {% client.global.set("registeredUserToken", response.body.token); %}
###

## Проверка токена пользователя
GET http://localhost:4200/users/login HTTP/1.1
Authorization: Bearer {{registeredUserToken}}
